### PR TITLE
Revert reversion for "Restrict cluster, machinepool and machinedeployment names"

### PR DESCRIPTION
**Pull request by mogottsch**
Reverts giantswarm/kyverno-policies-ux#44 (reverts the reversion PR)

We had to revert https://github.com/giantswarm/kyverno-policies-ux/pull/38, because some customers have machine deployments that start with a number.

**Update**:
After another investigation, we found that too many vintage installations violate these policies. Therefore, we decided to only roll out the policies for CAPI installations. 
The requirement for these policies originates from CAPI constraints, therefore we are OK with not having these in vintage.

### CODE REVIEW

**Comment by mogottsch** [comment]
Applying the policies to each MC yields the following results:

**MCs with problematic CRs**:
- golem

**MCs for which `opsctl login` did not work**:


| installation | problem                                                                                                                           |
|--------------|-----------------------------------------------------------------------------------------------------------------------------------|
| goat         | CA expired                                                                                                                        |
| icecream     | Post "https://athena.g8s.icecream.westeurope.azure.gigantic.io/graphql": EOF                                                      |
| gorgoth      | Post "https://athena.g8s.gorgoth.gridscale.kvm.gigantic.io/graphql": EOF                                                      |
| goten        | Post "https://athena.goten.gaws.gigantic.io/graphql": EOF                                                                         |
| goose        | Post "https://athena.goose.azuretest.gigantic.io/graphql": EOF                                                                    |
| gmc          | Post "https://athena.gmc.test.gigantic.io/graphql": dial tcp 10.10.222.140:443: connect: no route to host                         |
| gubble       | Post "https://athena.gubble.test.gigantic.io/graphql": context deadline exceeded (Client.Timeout exceeded while awaiting headers) |

I will try to fix the problematic CRs in `golem` and investigate why `opsctl login` does not work for the other ones.

**Comment by mogottsch** [comment]
Team Phoenix will take care of goat.
https://github.com/giantswarm/giantswarm/issues/27481

We wait with merging & releasing until that's done.

**Comment by mogottsch** [comment]
The problem with goat is fixed. This is ready to be released now.

**Comment by mogottsch** [comment]
I double-checked whether there are no resources that violate these policies and I overlooked some when first looking:

```
====================goku====================

Applying 4 policy rules to 15 resources...

policy cluster-names -> resource org-df-test/Cluster/2db3k failed: 
2. cluster-name-does-not-start-with-number: cluster name must not start with a number 

pass: 36, fail: 2, warn: 0, error: 0, skip: 41 
====================gollum====================

Applying 4 policy rules to 6 resources...

policy cluster-names -> resource org-giantswarm/Cluster/5jka7 failed: 
2. cluster-name-does-not-start-with-number: cluster name must not start with a number 

pass: 14, fail: 2, warn: 0, error: 0, skip: 16 
====================snail====================
W0816 08:30:18.157757   22269 warnings.go:70] cluster.x-k8s.io/v1alpha4 MachinePool is deprecated; use cluster.x-k8s.io/v1beta1 MachinePool
W0816 08:30:18.245199   22269 warnings.go:70] cluster.x-k8s.io/v1alpha4 MachineDeployment is deprecated; use cluster.x-k8s.io/v1beta1 MachineDeployment
W0816 08:30:18.312019   22269 warnings.go:70] cluster.x-k8s.io/v1alpha4 Cluster is deprecated; use cluster.x-k8s.io/v1beta1 Cluster
W0816 08:30:18.343854   22269 warnings.go:70] cluster.x-k8s.io/v1alpha3 MachineDeployment is deprecated; use cluster.x-k8s.io/v1beta1 MachineDeployment
W0816 08:30:18.382202   22269 warnings.go:70] cluster.x-k8s.io/v1alpha3 MachinePool is deprecated; use cluster.x-k8s.io/v1beta1 MachinePool
W0816 08:30:18.413439   22269 warnings.go:70] cluster.x-k8s.io/v1alpha3 Cluster is deprecated; use cluster.x-k8s.io/v1beta1 Cluster

Applying 4 policy rules to 8 resources...

policy cluster-names -> resource /Cluster/sample-customer failed: 
1. cluster-name-maximum-length: cluster name must be no longer than 10 characters 

policy cluster-names -> resource org-sample/Cluster/sample-customer failed: 
1. cluster-name-maximum-length: cluster name must be no longer than 10 characters 

pass: 18, fail: 4, warn: 0, error: 0, skip: 21 
====================viking====================

Applying 4 policy rules to 129 resources...

policy cluster-names -> resource org-apix-nonprod/Cluster/0d77f failed: 
2. cluster-name-does-not-start-with-number: cluster name must not start with a number 

policy cluster-names -> resource org-g-n-e/Cluster/3a77d failed: 
2. cluster-name-does-not-start-with-number: cluster name must not start with a number 

policy cluster-names -> resource org-rewards-prod/Cluster/21f0d failed: 
2. cluster-name-does-not-start-with-number: cluster name must not start with a number 

policy cluster-names -> resource org-securenet/Cluster/8c409 failed: 
2. cluster-name-does-not-start-with-number: cluster name must not start with a number 

policy cluster-names -> resource org-vodafone-id-prd/Cluster/3p5ny failed: 
2. cluster-name-does-not-start-with-number: cluster name must not start with a number 

policy cluster-names -> resource org-multi-tenant/Cluster/0ohqb failed: 
2. cluster-name-does-not-start-with-number: cluster name must not start with a number 

policy cluster-names -> resource org-vodafone-id/Cluster/2t4ky failed: 
2. cluster-name-does-not-start-with-number: cluster name must not start with a number 

policy cluster-names -> resource org-securenet/Cluster/7pf9a failed: 
2. cluster-name-does-not-start-with-number: cluster name must not start with a number 

policy cluster-names -> resource org-d-x-l/Cluster/48but failed: 
2. cluster-name-does-not-start-with-number: cluster name must not start with a number 

policy cluster-names -> resource org-algov-prod/Cluster/3d319 failed: 
2. cluster-name-does-not-start-with-number: cluster name must not start with a number 

policy cluster-names -> resource org-gateways-playground/Cluster/5e1e5 failed: 
2. cluster-name-does-not-start-with-number: cluster name must not start with a number 

policy cluster-names -> resource org-digital-pt/Cluster/7fkvu failed: 
2. cluster-name-does-not-start-with-number: cluster name must not start with a number 

policy cluster-names -> resource org-chatbot-nonprod/Cluster/0a452 failed: 
2. cluster-name-does-not-start-with-number: cluster name must not start with a number 

policy cluster-names -> resource org-d-x-l/Cluster/5y4cr failed: 
2. cluster-name-does-not-start-with-number: cluster name must not start with a number 

policy cluster-names -> resource org-g-i-g/Cluster/9vcqy failed: 
2. cluster-name-does-not-start-with-number: cluster name must not start with a number 

policy cluster-names -> resource org-vbps/Cluster/3pwt7 failed: 
2. cluster-name-does-not-start-with-number: cluster name must not start with a number 

pass: 320, fail: 32, warn: 0, error: 0, skip: 340 
```

**Review by anvddriesch — APPROVED** [review]

**Pull request merged**
